### ISSUE TITLE
Nodemon

### ISSUE THREAD

**Issue by LuluAylen00** [0623CIFSNCN05LAED/grupo-14#6]
Cuidado! Tienen instalado nodemon como dependencia regular. Sugeriría desinstalarlo como dependencia normal (`npm uninstall`) y dejarlo únicamente en el entorno de desarrollo (`npm i` con el `-D`). Por la misma corriente, podrían considerar añadir un script específico para correr el proyecto con nodemon (generalmente asignado en un script `"dev"`, cosa de correr el proyecto con `npm run dev`) y otro diferente para la ejecución normal en node (que si se encontraría en el script `"start"`)
https://github.com/0623CIFSNCN05LAED/grupo-14/blob/c90224f5b330087c6ce6a3286508a2ef9d17de9d/package.json#L6-L9
https://github.com/0623CIFSNCN05LAED/grupo-14/blob/c90224f5b330087c6ce6a3286508a2ef9d17de9d/package.json#L13-L18

**Comment by ManuelMarienhoff** [comment]
Se instalan la dependencia en modo developer
