### ISSUE TITLE
Enlaces rotos

### ISSUE THREAD

**Issue by LuluAylen00** [0623CIFSNCN05LAED/grupo-14#7]
Traten de, siempre que añaden nuevas funcionalidades (como puede ser el añadido de nuevas rutas, y su dinamismo), de asegurarse que las funcionalidades ya implementadas pueden seguir funcionando.
En este caso, al añadir las rutas parametrizadas, los enlaces que tienen en la homepage están rotos, debido a que no van al producto que se encontraría de forma dinámica (en español: se obtiene un `Cannot GET` al darle click a cualquiera de estos productos)
https://github.com/0623CIFSNCN05LAED/grupo-14/blob/c90224f5b330087c6ce6a3286508a2ef9d17de9d/src/views/main/homeCf.ejs#L62-L66

**Comment by ManuelMarienhoff** [comment]
Se reparan los enlaces de los productos de la pagina home. Falta darle un toque de estilo al carrusel pero esta en proceso.
